name: Deploy to LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4571:4571
        env:
          SERVICES: s3,lambda,dynamodb,cloudformation,iam,logs
          DEBUG: 1
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests radon 

      - name: Package Lambda functions
        run: |
          zip -r code_ingestion.zip code_ingestion.py
          zip -r code_quality_metrics.zip code_quality_metrics.py
          zip -r word_suggestions.zip word_suggestions.py

      - name: Configure AWS CLI for LocalStack
        run: |
          aws configure set aws_access_key_id test_id --profile localstack
          aws configure set aws_secret_access_key test_key --profile localstack
          aws configure set region us-east-1 --profile localstack
          aws configure set output json --profile localstack

      - name: Upload to S3 (LocalStack)
        run: |
          aws --endpoint-url=http://localhost:4566 s3 mb s3://git-radar-code-storage --profile localstack
          aws --endpoint-url=http://localhost:4566 s3 mb s3://git-radar-analysis-results --profile localstack
          aws --endpoint-url=http://localhost:4566 s3 cp code_ingestion.zip s3://git-radar-code-storage/code_ingestion.zip --profile localstack
          aws --endpoint-url=http://localhost:4566 s3 cp code_quality_metrics.zip s3://git-radar-code-storage/code_quality_metrics.zip --profile localstack
          aws --endpoint-url=http://localhost:4566 s3 cp word_suggestions.zip s3://git-radar-code-storage/word_suggestions.zip --profile localstack

      - name: Deploy CloudFormation stack (LocalStack)
        run: |
          aws --endpoint-url=http://localhost:4566 cloudformation create-stack \
            --stack-name GitRadarStack \
            --template-body file://template.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --profile localstack

