name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests radon sqlalchemy pymysql moto pytest

      - name: Package Lambda functions
        run: |
          zip -r code_ingestion.zip code_ingestion.py
          zip -r code_quality_metrics.zip code_quality_metrics.py
          zip -r word_suggestions.zip word_suggestions.py

      - name: Upload to S3
        run: |
          aws s3 cp code_ingestion.zip s3://git-radar-code-storage/code_ingestion.zip
          aws s3 cp code_quality_metrics.zip s3://git-radar-code-storage/code_quality_metrics.zip
          aws s3 cp word_suggestions.zip s3://git-radar-code-storage/word_suggestions.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name GitRadarStack \
            --capabilities CAPABILITY_NAMED_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

